// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: test/semantic_types/example.proto

package semantic_types

import (
	_ "github.com/streamingfast/substreams-sink-sql/pb/sf/substreams/sink/sql/schema/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Example demonstrating semantic type annotations for RisingWave rw_int256 support
type Output struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entities      []*Entity              `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Output) Reset() {
	*x = Output{}
	mi := &file_test_semantic_types_example_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Output) ProtoMessage() {}

func (x *Output) ProtoReflect() protoreflect.Message {
	mi := &file_test_semantic_types_example_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Output.ProtoReflect.Descriptor instead.
func (*Output) Descriptor() ([]byte, []int) {
	return file_test_semantic_types_example_proto_rawDescGZIP(), []int{0}
}

func (x *Output) GetEntities() []*Entity {
	if x != nil {
		return x.Entities
	}
	return nil
}

type Entity struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Entity:
	//
	//	*Entity_EthTransaction
	//	*Entity_Erc20Transfer
	//	*Entity_DefiPosition
	//	*Entity_MetricsData
	Entity        isEntity_Entity `protobuf_oneof:"entity"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entity) Reset() {
	*x = Entity{}
	mi := &file_test_semantic_types_example_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entity) ProtoMessage() {}

func (x *Entity) ProtoReflect() protoreflect.Message {
	mi := &file_test_semantic_types_example_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entity.ProtoReflect.Descriptor instead.
func (*Entity) Descriptor() ([]byte, []int) {
	return file_test_semantic_types_example_proto_rawDescGZIP(), []int{1}
}

func (x *Entity) GetEntity() isEntity_Entity {
	if x != nil {
		return x.Entity
	}
	return nil
}

func (x *Entity) GetEthTransaction() *EthereumTransaction {
	if x != nil {
		if x, ok := x.Entity.(*Entity_EthTransaction); ok {
			return x.EthTransaction
		}
	}
	return nil
}

func (x *Entity) GetErc20Transfer() *ERC20Transfer {
	if x != nil {
		if x, ok := x.Entity.(*Entity_Erc20Transfer); ok {
			return x.Erc20Transfer
		}
	}
	return nil
}

func (x *Entity) GetDefiPosition() *DeFiPosition {
	if x != nil {
		if x, ok := x.Entity.(*Entity_DefiPosition); ok {
			return x.DefiPosition
		}
	}
	return nil
}

func (x *Entity) GetMetricsData() *MetricsData {
	if x != nil {
		if x, ok := x.Entity.(*Entity_MetricsData); ok {
			return x.MetricsData
		}
	}
	return nil
}

type isEntity_Entity interface {
	isEntity_Entity()
}

type Entity_EthTransaction struct {
	EthTransaction *EthereumTransaction `protobuf:"bytes,1,opt,name=eth_transaction,json=ethTransaction,proto3,oneof"`
}

type Entity_Erc20Transfer struct {
	Erc20Transfer *ERC20Transfer `protobuf:"bytes,2,opt,name=erc20_transfer,json=erc20Transfer,proto3,oneof"`
}

type Entity_DefiPosition struct {
	DefiPosition *DeFiPosition `protobuf:"bytes,3,opt,name=defi_position,json=defiPosition,proto3,oneof"`
}

type Entity_MetricsData struct {
	MetricsData *MetricsData `protobuf:"bytes,4,opt,name=metrics_data,json=metricsData,proto3,oneof"`
}

func (*Entity_EthTransaction) isEntity_Entity() {}

func (*Entity_Erc20Transfer) isEntity_Entity() {}

func (*Entity_DefiPosition) isEntity_Entity() {}

func (*Entity_MetricsData) isEntity_Entity() {}

// Ethereum transaction with semantic types optimized for RisingWave
type EthereumTransaction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Transaction hash - optimized storage for 32-byte hashes
	Hash string `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	// Block hash
	BlockHash string `protobuf:"bytes,2,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	// Transaction value in wei - uses RisingWave's rw_int256 for large numbers
	Value string `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	// Gas price in wei - also uses rw_int256
	GasPrice string `protobuf:"bytes,4,opt,name=gas_price,json=gasPrice,proto3" json:"gas_price,omitempty"`
	// From address - optimized VARCHAR(42) storage
	FromAddress string `protobuf:"bytes,5,opt,name=from_address,json=fromAddress,proto3" json:"from_address,omitempty"`
	// To address
	ToAddress string `protobuf:"bytes,6,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`
	// Input data as hex
	InputData string `protobuf:"bytes,7,opt,name=input_data,json=inputData,proto3" json:"input_data,omitempty"`
	// Block timestamp
	BlockTimestamp int64 `protobuf:"varint,8,opt,name=block_timestamp,json=blockTimestamp,proto3" json:"block_timestamp,omitempty"`
	// Gas used (regular integer, not 256-bit)
	GasUsed int64 `protobuf:"varint,9,opt,name=gas_used,json=gasUsed,proto3" json:"gas_used,omitempty"`
	// Transaction index in block
	TransactionIndex int32 `protobuf:"varint,10,opt,name=transaction_index,json=transactionIndex,proto3" json:"transaction_index,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EthereumTransaction) Reset() {
	*x = EthereumTransaction{}
	mi := &file_test_semantic_types_example_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EthereumTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EthereumTransaction) ProtoMessage() {}

func (x *EthereumTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_test_semantic_types_example_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EthereumTransaction.ProtoReflect.Descriptor instead.
func (*EthereumTransaction) Descriptor() ([]byte, []int) {
	return file_test_semantic_types_example_proto_rawDescGZIP(), []int{2}
}

func (x *EthereumTransaction) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *EthereumTransaction) GetBlockHash() string {
	if x != nil {
		return x.BlockHash
	}
	return ""
}

func (x *EthereumTransaction) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *EthereumTransaction) GetGasPrice() string {
	if x != nil {
		return x.GasPrice
	}
	return ""
}

func (x *EthereumTransaction) GetFromAddress() string {
	if x != nil {
		return x.FromAddress
	}
	return ""
}

func (x *EthereumTransaction) GetToAddress() string {
	if x != nil {
		return x.ToAddress
	}
	return ""
}

func (x *EthereumTransaction) GetInputData() string {
	if x != nil {
		return x.InputData
	}
	return ""
}

func (x *EthereumTransaction) GetBlockTimestamp() int64 {
	if x != nil {
		return x.BlockTimestamp
	}
	return 0
}

func (x *EthereumTransaction) GetGasUsed() int64 {
	if x != nil {
		return x.GasUsed
	}
	return 0
}

func (x *EthereumTransaction) GetTransactionIndex() int32 {
	if x != nil {
		return x.TransactionIndex
	}
	return 0
}

// ERC20 transfer events with precise decimal handling
type ERC20Transfer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Contract address
	ContractAddress string `protobuf:"bytes,1,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
	// From address
	FromAddress string `protobuf:"bytes,2,opt,name=from_address,json=fromAddress,proto3" json:"from_address,omitempty"`
	// To address
	ToAddress string `protobuf:"bytes,3,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`
	// Transfer amount - 18 decimal places for most ERC20 tokens
	Amount string `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	// USDC amount example - 6 decimal places
	UsdcAmount string `protobuf:"bytes,5,opt,name=usdc_amount,json=usdcAmount,proto3" json:"usdc_amount,omitempty"`
	// Log index in transaction
	LogIndex      int32 `protobuf:"varint,6,opt,name=log_index,json=logIndex,proto3" json:"log_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ERC20Transfer) Reset() {
	*x = ERC20Transfer{}
	mi := &file_test_semantic_types_example_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ERC20Transfer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ERC20Transfer) ProtoMessage() {}

func (x *ERC20Transfer) ProtoReflect() protoreflect.Message {
	mi := &file_test_semantic_types_example_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ERC20Transfer.ProtoReflect.Descriptor instead.
func (*ERC20Transfer) Descriptor() ([]byte, []int) {
	return file_test_semantic_types_example_proto_rawDescGZIP(), []int{3}
}

func (x *ERC20Transfer) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *ERC20Transfer) GetFromAddress() string {
	if x != nil {
		return x.FromAddress
	}
	return ""
}

func (x *ERC20Transfer) GetToAddress() string {
	if x != nil {
		return x.ToAddress
	}
	return ""
}

func (x *ERC20Transfer) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *ERC20Transfer) GetUsdcAmount() string {
	if x != nil {
		return x.UsdcAmount
	}
	return ""
}

func (x *ERC20Transfer) GetLogIndex() int32 {
	if x != nil {
		return x.LogIndex
	}
	return 0
}

// DeFi position with various numeric types
type DeFiPosition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Position ID as UUID
	PositionId string `protobuf:"bytes,1,opt,name=position_id,json=positionId,proto3" json:"position_id,omitempty"`
	// User address
	UserAddress string `protobuf:"bytes,2,opt,name=user_address,json=userAddress,proto3" json:"user_address,omitempty"`
	// Protocol address
	ProtocolAddress string `protobuf:"bytes,3,opt,name=protocol_address,json=protocolAddress,proto3" json:"protocol_address,omitempty"`
	// Collateral amount (18 decimals)
	CollateralAmount string `protobuf:"bytes,4,opt,name=collateral_amount,json=collateralAmount,proto3" json:"collateral_amount,omitempty"`
	// Debt amount (18 decimals)
	DebtAmount string `protobuf:"bytes,5,opt,name=debt_amount,json=debtAmount,proto3" json:"debt_amount,omitempty"`
	// Liquidation threshold (percentage with 18 decimals)
	LiquidationThreshold string `protobuf:"bytes,6,opt,name=liquidation_threshold,json=liquidationThreshold,proto3" json:"liquidation_threshold,omitempty"`
	// Position metadata as JSON
	Metadata string `protobuf:"bytes,7,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Created timestamp
	CreatedAt int64 `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Updated timestamp (milliseconds)
	UpdatedAtMs   int64 `protobuf:"varint,9,opt,name=updated_at_ms,json=updatedAtMs,proto3" json:"updated_at_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeFiPosition) Reset() {
	*x = DeFiPosition{}
	mi := &file_test_semantic_types_example_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeFiPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeFiPosition) ProtoMessage() {}

func (x *DeFiPosition) ProtoReflect() protoreflect.Message {
	mi := &file_test_semantic_types_example_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeFiPosition.ProtoReflect.Descriptor instead.
func (*DeFiPosition) Descriptor() ([]byte, []int) {
	return file_test_semantic_types_example_proto_rawDescGZIP(), []int{4}
}

func (x *DeFiPosition) GetPositionId() string {
	if x != nil {
		return x.PositionId
	}
	return ""
}

func (x *DeFiPosition) GetUserAddress() string {
	if x != nil {
		return x.UserAddress
	}
	return ""
}

func (x *DeFiPosition) GetProtocolAddress() string {
	if x != nil {
		return x.ProtocolAddress
	}
	return ""
}

func (x *DeFiPosition) GetCollateralAmount() string {
	if x != nil {
		return x.CollateralAmount
	}
	return ""
}

func (x *DeFiPosition) GetDebtAmount() string {
	if x != nil {
		return x.DebtAmount
	}
	return ""
}

func (x *DeFiPosition) GetLiquidationThreshold() string {
	if x != nil {
		return x.LiquidationThreshold
	}
	return ""
}

func (x *DeFiPosition) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

func (x *DeFiPosition) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *DeFiPosition) GetUpdatedAtMs() int64 {
	if x != nil {
		return x.UpdatedAtMs
	}
	return 0
}

// Metrics and monitoring data
type MetricsData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Metric ID
	MetricId string `protobuf:"bytes,1,opt,name=metric_id,json=metricId,proto3" json:"metric_id,omitempty"`
	// Total value locked in protocol (money type for USD values)
	TvlUsd string `protobuf:"bytes,2,opt,name=tvl_usd,json=tvlUsd,proto3" json:"tvl_usd,omitempty"`
	// Bitcoin amount (8 decimal places)
	BtcAmount string `protobuf:"bytes,3,opt,name=btc_amount,json=btcAmount,proto3" json:"btc_amount,omitempty"`
	// Large integer metric (uses rw_int256)
	LargeMetric string `protobuf:"bytes,4,opt,name=large_metric,json=largeMetric,proto3" json:"large_metric,omitempty"`
	// Binary data
	BinaryData string `protobuf:"bytes,5,opt,name=binary_data,json=binaryData,proto3" json:"binary_data,omitempty"`
	// Signature data
	Signature string `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`
	// Public key
	PublicKey string `protobuf:"bytes,7,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	// Measurement timestamp
	MeasuredAt    int64 `protobuf:"varint,8,opt,name=measured_at,json=measuredAt,proto3" json:"measured_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsData) Reset() {
	*x = MetricsData{}
	mi := &file_test_semantic_types_example_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsData) ProtoMessage() {}

func (x *MetricsData) ProtoReflect() protoreflect.Message {
	mi := &file_test_semantic_types_example_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsData.ProtoReflect.Descriptor instead.
func (*MetricsData) Descriptor() ([]byte, []int) {
	return file_test_semantic_types_example_proto_rawDescGZIP(), []int{5}
}

func (x *MetricsData) GetMetricId() string {
	if x != nil {
		return x.MetricId
	}
	return ""
}

func (x *MetricsData) GetTvlUsd() string {
	if x != nil {
		return x.TvlUsd
	}
	return ""
}

func (x *MetricsData) GetBtcAmount() string {
	if x != nil {
		return x.BtcAmount
	}
	return ""
}

func (x *MetricsData) GetLargeMetric() string {
	if x != nil {
		return x.LargeMetric
	}
	return ""
}

func (x *MetricsData) GetBinaryData() string {
	if x != nil {
		return x.BinaryData
	}
	return ""
}

func (x *MetricsData) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *MetricsData) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *MetricsData) GetMeasuredAt() int64 {
	if x != nil {
		return x.MeasuredAt
	}
	return 0
}

var File_test_semantic_types_example_proto protoreflect.FileDescriptor

const file_test_semantic_types_example_proto_rawDesc = "" +
	"\n" +
	"!test/semantic_types/example.proto\x12\x13test.semantic_types\x1a\x1fgoogle/protobuf/timestamp.proto\x1a-sf/substreams/sink/sql/schema/v1/schema.proto\"A\n" +
	"\x06Output\x127\n" +
	"\bentities\x18\x01 \x03(\v2\x1b.test.semantic_types.EntityR\bentities\"\xc5\x02\n" +
	"\x06Entity\x12S\n" +
	"\x0feth_transaction\x18\x01 \x01(\v2(.test.semantic_types.EthereumTransactionH\x00R\x0eethTransaction\x12K\n" +
	"\x0eerc20_transfer\x18\x02 \x01(\v2\".test.semantic_types.ERC20TransferH\x00R\rerc20Transfer\x12H\n" +
	"\rdefi_position\x18\x03 \x01(\v2!.test.semantic_types.DeFiPositionH\x00R\fdefiPosition\x12E\n" +
	"\fmetrics_data\x18\x04 \x01(\v2 .test.semantic_types.MetricsDataH\x00R\vmetricsDataB\b\n" +
	"\x06entity\"\xf7\x03\n" +
	"\x13EthereumTransaction\x12)\n" +
	"\x04hash\x18\x01 \x01(\tB\x15\xb2\xf8%\x11\n" +
	"\atx_hash \x01*\x04hashR\x04hash\x12)\n" +
	"\n" +
	"block_hash\x18\x02 \x01(\tB\n" +
	"\xb2\xf8%\x06*\x04hashR\tblockHash\x12,\n" +
	"\x05value\x18\x03 \x01(\tB\x16\xb2\xf8%\x12*\auint2562\adecimalR\x05value\x123\n" +
	"\tgas_price\x18\x04 \x01(\tB\x16\xb2\xf8%\x12*\auint2562\adecimalR\bgasPrice\x120\n" +
	"\ffrom_address\x18\x05 \x01(\tB\r\xb2\xf8%\t*\aaddressR\vfromAddress\x12,\n" +
	"\n" +
	"to_address\x18\x06 \x01(\tB\r\xb2\xf8%\t*\aaddressR\ttoAddress\x12(\n" +
	"\n" +
	"input_data\x18\a \x01(\tB\t\xb2\xf8%\x05*\x03hexR\tinputData\x12=\n" +
	"\x0fblock_timestamp\x18\b \x01(\x03B\x14\xb2\xf8%\x10*\x0eunix_timestampR\x0eblockTimestamp\x12\x19\n" +
	"\bgas_used\x18\t \x01(\x03R\agasUsed\x12+\n" +
	"\x11transaction_index\x18\n" +
	" \x01(\x05R\x10transactionIndex:\x16\xaa\xf8%\x12\n" +
	"\x10eth_transactions\"\xe6\x02\n" +
	"\rERC20Transfer\x128\n" +
	"\x10contract_address\x18\x01 \x01(\tB\r\xb2\xf8%\t*\aaddressR\x0fcontractAddress\x120\n" +
	"\ffrom_address\x18\x02 \x01(\tB\r\xb2\xf8%\t*\aaddressR\vfromAddress\x12,\n" +
	"\n" +
	"to_address\x18\x03 \x01(\tB\r\xb2\xf8%\t*\aaddressR\ttoAddress\x120\n" +
	"\x06amount\x18\x04 \x01(\tB\x18\xb2\xf8%\x14*\tdecimal182\adecimalR\x06amount\x128\n" +
	"\vusdc_amount\x18\x05 \x01(\tB\x17\xb2\xf8%\x13*\bdecimal62\adecimalR\n" +
	"usdcAmount\x12\x1b\n" +
	"\tlog_index\x18\x06 \x01(\x05R\blogIndex:2\xaa\xf8%.\n" +
	"\x0ferc20_transfers\x12\x1beth_transactions on tx_hash\"\x8f\x04\n" +
	"\fDeFiPosition\x12-\n" +
	"\vposition_id\x18\x01 \x01(\tB\f\xb2\xf8%\b \x01*\x04uuidR\n" +
	"positionId\x120\n" +
	"\fuser_address\x18\x02 \x01(\tB\r\xb2\xf8%\t*\aaddressR\vuserAddress\x128\n" +
	"\x10protocol_address\x18\x03 \x01(\tB\r\xb2\xf8%\t*\aaddressR\x0fprotocolAddress\x12<\n" +
	"\x11collateral_amount\x18\x04 \x01(\tB\x0f\xb2\xf8%\v*\tdecimal18R\x10collateralAmount\x120\n" +
	"\vdebt_amount\x18\x05 \x01(\tB\x0f\xb2\xf8%\v*\tdecimal18R\n" +
	"debtAmount\x12D\n" +
	"\x15liquidation_threshold\x18\x06 \x01(\tB\x0f\xb2\xf8%\v*\tdecimal18R\x14liquidationThreshold\x12&\n" +
	"\bmetadata\x18\a \x01(\tB\n" +
	"\xb2\xf8%\x06*\x04jsonR\bmetadata\x123\n" +
	"\n" +
	"created_at\x18\b \x01(\x03B\x14\xb2\xf8%\x10*\x0eunix_timestampR\tcreatedAt\x12;\n" +
	"\rupdated_at_ms\x18\t \x01(\x03B\x17\xb2\xf8%\x13*\x11unix_timestamp_msR\vupdatedAtMs:\x14\xaa\xf8%\x10\n" +
	"\x0edefi_positions\"\x99\x03\n" +
	"\vMetricsData\x12)\n" +
	"\tmetric_id\x18\x01 \x01(\tB\f\xb2\xf8%\b \x01*\x04uuidR\bmetricId\x12$\n" +
	"\atvl_usd\x18\x02 \x01(\tB\v\xb2\xf8%\a*\x05moneyR\x06tvlUsd\x12-\n" +
	"\n" +
	"btc_amount\x18\x03 \x01(\tB\x0e\xb2\xf8%\n" +
	"*\bdecimal8R\tbtcAmount\x128\n" +
	"\flarge_metric\x18\x04 \x01(\tB\x15\xb2\xf8%\x11*\x06int2562\adecimalR\vlargeMetric\x12-\n" +
	"\vbinary_data\x18\x05 \x01(\tB\f\xb2\xf8%\b*\x06base64R\n" +
	"binaryData\x12-\n" +
	"\tsignature\x18\x06 \x01(\tB\x0f\xb2\xf8%\v*\tsignatureR\tsignature\x12+\n" +
	"\n" +
	"public_key\x18\a \x01(\tB\f\xb2\xf8%\b*\x06pubkeyR\tpublicKey\x126\n" +
	"\vmeasured_at\x18\b \x01(\x03B\x15\xb2\xf8%\x11*\x0fblock_timestampR\n" +
	"measuredAt:\r\xaa\xf8%\t\n" +
	"\ametricsB\xa5\x01\n" +
	"\x17com.test.semantic_typesB\fExampleProtoP\x01Z\x13test/semantic_types\xa2\x02\x03TSX\xaa\x02\x12Test.SemanticTypes\xca\x02\x12Test\\SemanticTypes\xe2\x02\x1eTest\\SemanticTypes\\GPBMetadata\xea\x02\x13Test::SemanticTypesb\x06proto3"

var (
	file_test_semantic_types_example_proto_rawDescOnce sync.Once
	file_test_semantic_types_example_proto_rawDescData []byte
)

func file_test_semantic_types_example_proto_rawDescGZIP() []byte {
	file_test_semantic_types_example_proto_rawDescOnce.Do(func() {
		file_test_semantic_types_example_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_test_semantic_types_example_proto_rawDesc), len(file_test_semantic_types_example_proto_rawDesc)))
	})
	return file_test_semantic_types_example_proto_rawDescData
}

var file_test_semantic_types_example_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_test_semantic_types_example_proto_goTypes = []any{
	(*Output)(nil),              // 0: test.semantic_types.Output
	(*Entity)(nil),              // 1: test.semantic_types.Entity
	(*EthereumTransaction)(nil), // 2: test.semantic_types.EthereumTransaction
	(*ERC20Transfer)(nil),       // 3: test.semantic_types.ERC20Transfer
	(*DeFiPosition)(nil),        // 4: test.semantic_types.DeFiPosition
	(*MetricsData)(nil),         // 5: test.semantic_types.MetricsData
}
var file_test_semantic_types_example_proto_depIdxs = []int32{
	1, // 0: test.semantic_types.Output.entities:type_name -> test.semantic_types.Entity
	2, // 1: test.semantic_types.Entity.eth_transaction:type_name -> test.semantic_types.EthereumTransaction
	3, // 2: test.semantic_types.Entity.erc20_transfer:type_name -> test.semantic_types.ERC20Transfer
	4, // 3: test.semantic_types.Entity.defi_position:type_name -> test.semantic_types.DeFiPosition
	5, // 4: test.semantic_types.Entity.metrics_data:type_name -> test.semantic_types.MetricsData
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_test_semantic_types_example_proto_init() }
func file_test_semantic_types_example_proto_init() {
	if File_test_semantic_types_example_proto != nil {
		return
	}
	file_test_semantic_types_example_proto_msgTypes[1].OneofWrappers = []any{
		(*Entity_EthTransaction)(nil),
		(*Entity_Erc20Transfer)(nil),
		(*Entity_DefiPosition)(nil),
		(*Entity_MetricsData)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_test_semantic_types_example_proto_rawDesc), len(file_test_semantic_types_example_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_test_semantic_types_example_proto_goTypes,
		DependencyIndexes: file_test_semantic_types_example_proto_depIdxs,
		MessageInfos:      file_test_semantic_types_example_proto_msgTypes,
	}.Build()
	File_test_semantic_types_example_proto = out.File
	file_test_semantic_types_example_proto_goTypes = nil
	file_test_semantic_types_example_proto_depIdxs = nil
}
