package main

import (
	"strings"
	"testing"

	"github.com/golang/protobuf/proto"
	"github.com/golang/protobuf/protoc-gen-go/descriptor"
	"github.com/jhump/protoreflect/desc"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"github.com/streamingfast/substreams-sink-sql/db_proto/sql"
	"github.com/streamingfast/substreams-sink-sql/db_proto/sql/postgres"
	"github.com/streamingfast/substreams-sink-sql/db_proto/sql/risingwave"
	"github.com/streamingfast/substreams-sink-sql/db_proto/sql/schema"
	"go.uber.org/zap"
)

// TestFromProtoGenerateCSVCompatibility ensures that the SQL generated by from-proto-generate-csv
// matches what from-proto would create
func TestFromProtoGenerateCSVCompatibility(t *testing.T) {
	logger := zap.NewNop()

	// Create a test schema with a simple table
	testSchema := &schema.Schema{
		Name:          "test_schema",
		TableRegistry: make(map[string]*schema.Table),
	}

	// Create a simple test table
	testTable := &schema.Table{
		Name: "test_table",
		Columns: []*schema.Column{
			{
				Name:            "id",
				IsPrimaryKey:    true,
				FieldDescriptor: createTestFieldDescriptor("id", descriptor.FieldDescriptorProto_TYPE_INT64),
			},
			{
				Name:            "name",
				FieldDescriptor: createTestFieldDescriptor("name", descriptor.FieldDescriptorProto_TYPE_STRING),
			},
			{
				Name:            "amount",
				FieldDescriptor: createTestFieldDescriptor("amount", descriptor.FieldDescriptorProto_TYPE_UINT64),
			},
		},
		PrimaryKey: &schema.PrimaryKey{
			Name:            "id",
			FieldDescriptor: createTestFieldDescriptor("id", descriptor.FieldDescriptorProto_TYPE_INT64),
		},
	}

	testSchema.TableRegistry["test_table"] = testTable

	// Create PostgreSQL dialect (same as from-proto would)
	dialect, err := postgres.NewDialectPostgres(testSchema, logger)
	require.NoError(t, err)

	// Export SQL schema
	var statements []string

	// Get static SQL
	staticSQL := getStaticSQL("postgres", testSchema.Name)
	if staticSQL != "" {
		statements = append(statements, staticSQL)
	}

	// Get table creation SQL
	baseDialect := dialect.BaseDialect
	for _, createSQL := range baseDialect.CreateTableSql {
		statements = append(statements, createSQL)
	}

	// Verify the SQL contains expected elements
	fullSQL := strings.Join(statements, "\n")

	// Check for schema creation
	assert.Contains(t, fullSQL, `CREATE SCHEMA IF NOT EXISTS "test_schema"`)

    // Check for system tables (match dialect static SQL, table names unquoted)
    assert.Contains(t, fullSQL, `CREATE TABLE IF NOT EXISTS "test_schema"._sink_info_`)
    assert.Contains(t, fullSQL, `CREATE TABLE IF NOT EXISTS "test_schema"._cursor_`)
    assert.Contains(t, fullSQL, `CREATE TABLE IF NOT EXISTS "test_schema"._blocks_`)

	// Check for user table with system columns
	assert.Contains(t, fullSQL, `_block_number_ INTEGER NOT NULL`)
	assert.Contains(t, fullSQL, `_block_timestamp_ TIMESTAMP NOT NULL`)

	// Check for user columns with correct types (with quotes as generated)
	assert.Contains(t, fullSQL, `id BIGINT`) // INT64 -> BIGINT
	assert.Contains(t, fullSQL, `"name" VARCHAR`) // STRING -> VARCHAR (with quotes)
	assert.Contains(t, fullSQL, `"amount" NUMERIC`) // UINT64 -> NUMERIC (with quotes)
}

// TestFromProtoGenerateCSVCompatibility_RisingWave ensures that the SQL generated by
// from-proto-generate-csv matches what the RisingWave dialect would create, and that
// system column names use the non-underscored variant.
func TestFromProtoGenerateCSVCompatibility_RisingWave(t *testing.T) {
    logger := zap.NewNop()

    // Build a simple schema
    testSchema := &schema.Schema{ Name: "test_schema", TableRegistry: make(map[string]*schema.Table) }
    testTable := &schema.Table{
        Name: "test_table",
        Columns: []*schema.Column{
            { Name: "id", IsPrimaryKey: true, FieldDescriptor: createTestFieldDescriptor("id", descriptor.FieldDescriptorProto_TYPE_INT64) },
            { Name: "name", FieldDescriptor: createTestFieldDescriptor("name", descriptor.FieldDescriptorProto_TYPE_STRING) },
            { Name: "amount", FieldDescriptor: createTestFieldDescriptor("amount", descriptor.FieldDescriptorProto_TYPE_UINT64) },
        },
        PrimaryKey: &schema.PrimaryKey{ Name: "id", FieldDescriptor: createTestFieldDescriptor("id", descriptor.FieldDescriptorProto_TYPE_INT64) },
    }
    testSchema.TableRegistry["test_table"] = testTable

    // Create RisingWave dialect
    dialect, err := risingwave.NewDialectRisingwave(testSchema.Name, testSchema.TableRegistry, logger)
    require.NoError(t, err)

    // Compose SQL similar to export path
    var statements []string
    staticSQL := getStaticSQL("risingwave", testSchema.Name)
    if staticSQL != "" {
        statements = append(statements, staticSQL)
    }
    baseDialect := dialect.BaseDialect
    for _, createSQL := range baseDialect.CreateTableSql {
        statements = append(statements, createSQL)
    }
    fullSQL := strings.Join(statements, "\n")

    // Schema creation present
    assert.Contains(t, fullSQL, `CREATE SCHEMA IF NOT EXISTS "test_schema"`)

    // System tables present
    assert.Contains(t, fullSQL, `CREATE TABLE IF NOT EXISTS "test_schema"._sink_info_`)
    assert.Contains(t, fullSQL, `CREATE TABLE IF NOT EXISTS "test_schema"._cursor_`)
    assert.Contains(t, fullSQL, `CREATE TABLE IF NOT EXISTS "test_schema"._blocks_`)

    // _blocks_ columns for RisingWave
    assert.Contains(t, fullSQL, "number INTEGER PRIMARY KEY")
    assert.Contains(t, fullSQL, "hash VARCHAR")
    assert.Contains(t, fullSQL, "timestamp TIMESTAMP WITH TIME ZONE")

    // User table system columns (non-underscored for RisingWave)
    assert.Contains(t, fullSQL, "block_number INTEGER")
    assert.Contains(t, fullSQL, "block_timestamp TIMESTAMP WITH TIME ZONE")
    assert.NotContains(t, fullSQL, "_block_number_")
    assert.NotContains(t, fullSQL, "_block_timestamp_")

    // User columns with correct types (id unquoted, others quoted by dialect)
    assert.Contains(t, fullSQL, "id BIGINT PRIMARY KEY")
    assert.Contains(t, fullSQL, `"name" CHARACTER VARYING`)
    assert.Contains(t, fullSQL, `"amount" NUMERIC`)
}

// TestCSVColumnOrder ensures CSV columns are in the exact order from-proto expects
func TestCSVColumnOrder(t *testing.T) {
	logger := zap.NewNop()

	// Create test schema
	testSchema := &schema.Schema{
		Name:          "test_schema",
		TableRegistry: make(map[string]*schema.Table),
	}

	testTable := &schema.Table{
		Name: "test_table",
		Columns: []*schema.Column{
			{
				Name:            "id",
				FieldDescriptor: createTestFieldDescriptor("id", descriptor.FieldDescriptorProto_TYPE_INT64),
			},
			{
				Name:            "name",
				FieldDescriptor: createTestFieldDescriptor("name", descriptor.FieldDescriptorProto_TYPE_STRING),
			},
		},
	}

	testSchema.TableRegistry["test_table"] = testTable

	// Create dialect
	dialect, err := postgres.NewDialectPostgres(testSchema, logger)
	require.NoError(t, err)

	// Create generator and get columns
	gen := &protoAwareCSVGenerator{
		schema:  testSchema,
		dialect: dialect,
		logger:  logger,
	}

	columns := gen.getColumnsForTable(testTable)

	// Verify column order: system columns first, then user columns
	expectedColumns := []string{
		sql.DialectFieldBlockNumber,    // "_block_number_"
		sql.DialectFieldBlockTimestamp, // "_block_timestamp_"
		"id",
		"name",
	}

	assert.Equal(t, expectedColumns, columns)
}

// TestCSVColumnOrder_RisingWave ensures CSV columns are in exact order for RisingWave
func TestCSVColumnOrder_RisingWave(t *testing.T) {
    logger := zap.NewNop()

    // Create test schema
    testSchema := &schema.Schema{
        Name:          "test_schema",
        TableRegistry: make(map[string]*schema.Table),
    }

    testTable := &schema.Table{
        Name: "test_table",
        Columns: []*schema.Column{
            {
                Name:            "id",
                FieldDescriptor: createTestFieldDescriptor("id", descriptor.FieldDescriptorProto_TYPE_INT64),
            },
            {
                Name:            "name",
                FieldDescriptor: createTestFieldDescriptor("name", descriptor.FieldDescriptorProto_TYPE_STRING),
            },
        },
    }

    testSchema.TableRegistry["test_table"] = testTable

    // Create RisingWave dialect
    dialect, err := risingwave.NewDialectRisingwave(testSchema.Name, testSchema.TableRegistry, logger)
    require.NoError(t, err)

    // Create generator and get columns
    gen := &protoAwareCSVGenerator{
        schema:  testSchema,
        dialect: dialect,
        logger:  logger,
    }

    columns := gen.getColumnsForTable(testTable)

    // Verify column order: system columns first (dialect-specific), then user columns
    expectedColumns := []string{
        "block_number",    // RisingWave names without underscores
        "block_timestamp",
        "id",
        "name",
    }

    assert.Equal(t, expectedColumns, columns)
}

// TestSchemaHashConsistency ensures schema hash is consistent
func TestSchemaHashConsistency(t *testing.T) {
	logger := zap.NewNop()

	// Create identical schemas
	schema1 := createTestSchema("test")
	schema2 := createTestSchema("test")

	// Create dialects
	dialect1, err := postgres.NewDialectPostgres(schema1, logger)
	require.NoError(t, err)

	dialect2, err := postgres.NewDialectPostgres(schema2, logger)
	require.NoError(t, err)

	// Hashes should be identical
	hash1 := dialect1.SchemaHash()
	hash2 := dialect2.SchemaHash()

	assert.Equal(t, hash1, hash2, "Schema hashes should be identical for same schema")
}

// Helper functions for testing

func createTestSchema(name string) *schema.Schema {
	s := &schema.Schema{
		Name:          name,
		TableRegistry: make(map[string]*schema.Table),
	}

	table := &schema.Table{
		Name: "test_table",
		Columns: []*schema.Column{
			{
				Name:            "id",
				IsPrimaryKey:    true,
				FieldDescriptor: createTestFieldDescriptor("id", descriptor.FieldDescriptorProto_TYPE_INT64),
			},
		},
	}

	s.TableRegistry["test_table"] = table
	return s
}

func createTestFieldDescriptor(name string, fieldType descriptor.FieldDescriptorProto_Type) *desc.FieldDescriptor {
	// Create a minimal field descriptor proto
	fdp := &descriptor.FieldDescriptorProto{
		Name:   &name,
		Number: proto.Int32(1),
		Type:   &fieldType,
	}

	// Create a minimal message descriptor proto to contain the field
	mdp := &descriptor.DescriptorProto{
		Name:  proto.String("TestMessage"),
		Field: []*descriptor.FieldDescriptorProto{fdp},
	}

	// Create a minimal file descriptor proto
	fileName := "test.proto"
	fdProto := &descriptor.FileDescriptorProto{
		Name:        &fileName,
		MessageType: []*descriptor.DescriptorProto{mdp},
	}

	// Create the file descriptor
	fd, err := desc.CreateFileDescriptor(fdProto)
	if err != nil {
		return nil
	}

	// Get the message descriptor and then the field descriptor
	msgDesc := fd.GetMessageTypes()[0]
	if msgDesc != nil && len(msgDesc.GetFields()) > 0 {
		return msgDesc.GetFields()[0]
	}

	return nil
}
