// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: sf/substreams/sink/sql/schema/v1/schema.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IndexType int32

const (
	IndexType_minmax       IndexType = 0
	IndexType_set          IndexType = 1
	IndexType_ngrambf_v1   IndexType = 2
	IndexType_tokenbf_v1   IndexType = 3
	IndexType_bloom_filter IndexType = 4
)

// Enum value maps for IndexType.
var (
	IndexType_name = map[int32]string{
		0: "minmax",
		1: "set",
		2: "ngrambf_v1",
		3: "tokenbf_v1",
		4: "bloom_filter",
	}
	IndexType_value = map[string]int32{
		"minmax":       0,
		"set":          1,
		"ngrambf_v1":   2,
		"tokenbf_v1":   3,
		"bloom_filter": 4,
	}
)

func (x IndexType) Enum() *IndexType {
	p := new(IndexType)
	*p = x
	return p
}

func (x IndexType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IndexType) Descriptor() protoreflect.EnumDescriptor {
	return file_sf_substreams_sink_sql_schema_v1_schema_proto_enumTypes[0].Descriptor()
}

func (IndexType) Type() protoreflect.EnumType {
	return &file_sf_substreams_sink_sql_schema_v1_schema_proto_enumTypes[0]
}

func (x IndexType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IndexType.Descriptor instead.
func (IndexType) EnumDescriptor() ([]byte, []int) {
	return file_sf_substreams_sink_sql_schema_v1_schema_proto_rawDescGZIP(), []int{0}
}

type Function int32

const (
	Function_unset          Function = 0
	Function_toYYYYMM       Function = 1
	Function_toYYYYDD       Function = 2
	Function_toYear         Function = 3
	Function_toMonth        Function = 4
	Function_toDate         Function = 5
	Function_toStartOfMonth Function = 6
)

// Enum value maps for Function.
var (
	Function_name = map[int32]string{
		0: "unset",
		1: "toYYYYMM",
		2: "toYYYYDD",
		3: "toYear",
		4: "toMonth",
		5: "toDate",
		6: "toStartOfMonth",
	}
	Function_value = map[string]int32{
		"unset":          0,
		"toYYYYMM":       1,
		"toYYYYDD":       2,
		"toYear":         3,
		"toMonth":        4,
		"toDate":         5,
		"toStartOfMonth": 6,
	}
)

func (x Function) Enum() *Function {
	p := new(Function)
	*p = x
	return p
}

func (x Function) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Function) Descriptor() protoreflect.EnumDescriptor {
	return file_sf_substreams_sink_sql_schema_v1_schema_proto_enumTypes[1].Descriptor()
}

func (Function) Type() protoreflect.EnumType {
	return &file_sf_substreams_sink_sql_schema_v1_schema_proto_enumTypes[1]
}

func (x Function) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Function.Descriptor instead.
func (Function) EnumDescriptor() ([]byte, []int) {
	return file_sf_substreams_sink_sql_schema_v1_schema_proto_rawDescGZIP(), []int{1}
}

// Storage layout options for RisingWave tables
type StorageLayout int32

const (
	StorageLayout_HUMMOCK StorageLayout = 0 // Default: Row-oriented streaming storage engine
	StorageLayout_ICEBERG StorageLayout = 1 // Columnar analytical storage with Iceberg integration
)

// Enum value maps for StorageLayout.
var (
	StorageLayout_name = map[int32]string{
		0: "HUMMOCK",
		1: "ICEBERG",
	}
	StorageLayout_value = map[string]int32{
		"HUMMOCK": 0,
		"ICEBERG": 1,
	}
)

func (x StorageLayout) Enum() *StorageLayout {
	p := new(StorageLayout)
	*p = x
	return p
}

func (x StorageLayout) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StorageLayout) Descriptor() protoreflect.EnumDescriptor {
	return file_sf_substreams_sink_sql_schema_v1_schema_proto_enumTypes[2].Descriptor()
}

func (StorageLayout) Type() protoreflect.EnumType {
	return &file_sf_substreams_sink_sql_schema_v1_schema_proto_enumTypes[2]
}

func (x StorageLayout) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StorageLayout.Descriptor instead.
func (StorageLayout) EnumDescriptor() ([]byte, []int) {
	return file_sf_substreams_sink_sql_schema_v1_schema_proto_rawDescGZIP(), []int{2}
}

type Table struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Name    string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ChildOf *string                `protobuf:"bytes,2,opt,name=child_of,json=childOf,proto3,oneof" json:"child_of,omitempty"`
	// repeated string primary_key_fields = 3;
	StorageLayout          *StorageLayout          `protobuf:"varint,4,opt,name=storage_layout,json=storageLayout,proto3,enum=sf.substreams.sink.sql.schema.v1.StorageLayout,oneof" json:"storage_layout,omitempty"` // RisingWave storage engine choice
	ClickhouseTableOptions *ClickhouseTableOptions `protobuf:"bytes,200,opt,name=clickhouse_table_options,json=clickhouseTableOptions,proto3,oneof" json:"clickhouse_table_options,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Table) Reset() {
	*x = Table{}
	mi := &file_sf_substreams_sink_sql_schema_v1_schema_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Table) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Table) ProtoMessage() {}

func (x *Table) ProtoReflect() protoreflect.Message {
	mi := &file_sf_substreams_sink_sql_schema_v1_schema_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Table.ProtoReflect.Descriptor instead.
func (*Table) Descriptor() ([]byte, []int) {
	return file_sf_substreams_sink_sql_schema_v1_schema_proto_rawDescGZIP(), []int{0}
}

func (x *Table) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Table) GetChildOf() string {
	if x != nil && x.ChildOf != nil {
		return *x.ChildOf
	}
	return ""
}

func (x *Table) GetStorageLayout() StorageLayout {
	if x != nil && x.StorageLayout != nil {
		return *x.StorageLayout
	}
	return StorageLayout_HUMMOCK
}

func (x *Table) GetClickhouseTableOptions() *ClickhouseTableOptions {
	if x != nil {
		return x.ClickhouseTableOptions
	}
	return nil
}

type Column struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Name       *string                `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	ForeignKey *string                `protobuf:"bytes,2,opt,name=foreign_key,json=foreignKey,proto3,oneof" json:"foreign_key,omitempty"`
	Unique     bool                   `protobuf:"varint,3,opt,name=unique,proto3" json:"unique,omitempty"`
	PrimaryKey bool                   `protobuf:"varint,4,opt,name=primary_key,json=primaryKey,proto3" json:"primary_key,omitempty"`
	// Semantic type annotation for custom SQL type mapping
	SemanticType  *string `protobuf:"bytes,5,opt,name=semantic_type,json=semanticType,proto3,oneof" json:"semantic_type,omitempty"` // Semantic type hint (e.g., "uint256", "address")
	FormatHint    *string `protobuf:"bytes,6,opt,name=format_hint,json=formatHint,proto3,oneof" json:"format_hint,omitempty"`       // Format hint for conversion (e.g., "hex", "decimal")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Column) Reset() {
	*x = Column{}
	mi := &file_sf_substreams_sink_sql_schema_v1_schema_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Column) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Column) ProtoMessage() {}

func (x *Column) ProtoReflect() protoreflect.Message {
	mi := &file_sf_substreams_sink_sql_schema_v1_schema_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Column.ProtoReflect.Descriptor instead.
func (*Column) Descriptor() ([]byte, []int) {
	return file_sf_substreams_sink_sql_schema_v1_schema_proto_rawDescGZIP(), []int{1}
}

func (x *Column) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *Column) GetForeignKey() string {
	if x != nil && x.ForeignKey != nil {
		return *x.ForeignKey
	}
	return ""
}

func (x *Column) GetUnique() bool {
	if x != nil {
		return x.Unique
	}
	return false
}

func (x *Column) GetPrimaryKey() bool {
	if x != nil {
		return x.PrimaryKey
	}
	return false
}

func (x *Column) GetSemanticType() string {
	if x != nil && x.SemanticType != nil {
		return *x.SemanticType
	}
	return ""
}

func (x *Column) GetFormatHint() string {
	if x != nil && x.FormatHint != nil {
		return *x.FormatHint
	}
	return ""
}

type ClickhouseTableOptions struct {
	state           protoimpl.MessageState        `protogen:"open.v1"`
	OrderByFields   []*ClickhouseOrderByField     `protobuf:"bytes,1,rep,name=order_by_fields,json=orderByFields,proto3" json:"order_by_fields,omitempty"`
	PartitionFields []*ClickhousePartitionByField `protobuf:"bytes,2,rep,name=partition_fields,json=partitionFields,proto3" json:"partition_fields,omitempty"`
	ReplacingFields []*ClickhouseReplacingField   `protobuf:"bytes,3,rep,name=replacing_fields,json=replacingFields,proto3" json:"replacing_fields,omitempty"`
	IndexFields     []*ClickhouseIndexField       `protobuf:"bytes,4,rep,name=index_fields,json=indexFields,proto3" json:"index_fields,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ClickhouseTableOptions) Reset() {
	*x = ClickhouseTableOptions{}
	mi := &file_sf_substreams_sink_sql_schema_v1_schema_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClickhouseTableOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClickhouseTableOptions) ProtoMessage() {}

func (x *ClickhouseTableOptions) ProtoReflect() protoreflect.Message {
	mi := &file_sf_substreams_sink_sql_schema_v1_schema_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClickhouseTableOptions.ProtoReflect.Descriptor instead.
func (*ClickhouseTableOptions) Descriptor() ([]byte, []int) {
	return file_sf_substreams_sink_sql_schema_v1_schema_proto_rawDescGZIP(), []int{2}
}

func (x *ClickhouseTableOptions) GetOrderByFields() []*ClickhouseOrderByField {
	if x != nil {
		return x.OrderByFields
	}
	return nil
}

func (x *ClickhouseTableOptions) GetPartitionFields() []*ClickhousePartitionByField {
	if x != nil {
		return x.PartitionFields
	}
	return nil
}

func (x *ClickhouseTableOptions) GetReplacingFields() []*ClickhouseReplacingField {
	if x != nil {
		return x.ReplacingFields
	}
	return nil
}

func (x *ClickhouseTableOptions) GetIndexFields() []*ClickhouseIndexField {
	if x != nil {
		return x.IndexFields
	}
	return nil
}

type ClickhousePartitionByField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Function      Function               `protobuf:"varint,2,opt,name=function,proto3,enum=sf.substreams.sink.sql.schema.v1.Function" json:"function,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClickhousePartitionByField) Reset() {
	*x = ClickhousePartitionByField{}
	mi := &file_sf_substreams_sink_sql_schema_v1_schema_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClickhousePartitionByField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClickhousePartitionByField) ProtoMessage() {}

func (x *ClickhousePartitionByField) ProtoReflect() protoreflect.Message {
	mi := &file_sf_substreams_sink_sql_schema_v1_schema_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClickhousePartitionByField.ProtoReflect.Descriptor instead.
func (*ClickhousePartitionByField) Descriptor() ([]byte, []int) {
	return file_sf_substreams_sink_sql_schema_v1_schema_proto_rawDescGZIP(), []int{3}
}

func (x *ClickhousePartitionByField) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ClickhousePartitionByField) GetFunction() Function {
	if x != nil {
		return x.Function
	}
	return Function_unset
}

type ClickhouseOrderByField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Descending    bool                   `protobuf:"varint,2,opt,name=descending,proto3" json:"descending,omitempty"`
	Function      Function               `protobuf:"varint,3,opt,name=function,proto3,enum=sf.substreams.sink.sql.schema.v1.Function" json:"function,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClickhouseOrderByField) Reset() {
	*x = ClickhouseOrderByField{}
	mi := &file_sf_substreams_sink_sql_schema_v1_schema_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClickhouseOrderByField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClickhouseOrderByField) ProtoMessage() {}

func (x *ClickhouseOrderByField) ProtoReflect() protoreflect.Message {
	mi := &file_sf_substreams_sink_sql_schema_v1_schema_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClickhouseOrderByField.ProtoReflect.Descriptor instead.
func (*ClickhouseOrderByField) Descriptor() ([]byte, []int) {
	return file_sf_substreams_sink_sql_schema_v1_schema_proto_rawDescGZIP(), []int{4}
}

func (x *ClickhouseOrderByField) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ClickhouseOrderByField) GetDescending() bool {
	if x != nil {
		return x.Descending
	}
	return false
}

func (x *ClickhouseOrderByField) GetFunction() Function {
	if x != nil {
		return x.Function
	}
	return Function_unset
}

type ClickhouseReplacingField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClickhouseReplacingField) Reset() {
	*x = ClickhouseReplacingField{}
	mi := &file_sf_substreams_sink_sql_schema_v1_schema_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClickhouseReplacingField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClickhouseReplacingField) ProtoMessage() {}

func (x *ClickhouseReplacingField) ProtoReflect() protoreflect.Message {
	mi := &file_sf_substreams_sink_sql_schema_v1_schema_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClickhouseReplacingField.ProtoReflect.Descriptor instead.
func (*ClickhouseReplacingField) Descriptor() ([]byte, []int) {
	return file_sf_substreams_sink_sql_schema_v1_schema_proto_rawDescGZIP(), []int{5}
}

func (x *ClickhouseReplacingField) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ClickhouseIndexField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	FieldName     string                 `protobuf:"bytes,2,opt,name=field_name,json=fieldName,proto3" json:"field_name,omitempty"`
	Type          IndexType              `protobuf:"varint,3,opt,name=type,proto3,enum=sf.substreams.sink.sql.schema.v1.IndexType" json:"type,omitempty"`
	Granularity   uint32                 `protobuf:"varint,4,opt,name=granularity,proto3" json:"granularity,omitempty"`
	Function      Function               `protobuf:"varint,5,opt,name=function,proto3,enum=sf.substreams.sink.sql.schema.v1.Function" json:"function,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClickhouseIndexField) Reset() {
	*x = ClickhouseIndexField{}
	mi := &file_sf_substreams_sink_sql_schema_v1_schema_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClickhouseIndexField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClickhouseIndexField) ProtoMessage() {}

func (x *ClickhouseIndexField) ProtoReflect() protoreflect.Message {
	mi := &file_sf_substreams_sink_sql_schema_v1_schema_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClickhouseIndexField.ProtoReflect.Descriptor instead.
func (*ClickhouseIndexField) Descriptor() ([]byte, []int) {
	return file_sf_substreams_sink_sql_schema_v1_schema_proto_rawDescGZIP(), []int{6}
}

func (x *ClickhouseIndexField) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ClickhouseIndexField) GetFieldName() string {
	if x != nil {
		return x.FieldName
	}
	return ""
}

func (x *ClickhouseIndexField) GetType() IndexType {
	if x != nil {
		return x.Type
	}
	return IndexType_minmax
}

func (x *ClickhouseIndexField) GetGranularity() uint32 {
	if x != nil {
		return x.Granularity
	}
	return 0
}

func (x *ClickhouseIndexField) GetFunction() Function {
	if x != nil {
		return x.Function
	}
	return Function_unset
}

var file_sf_substreams_sink_sql_schema_v1_schema_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*Table)(nil),
		Field:         77701,
		Name:          "sf.substreams.sink.sql.schema.v1.table",
		Tag:           "bytes,77701,opt,name=table",
		Filename:      "sf/substreams/sink/sql/schema/v1/schema.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*Column)(nil),
		Field:         77702,
		Name:          "sf.substreams.sink.sql.schema.v1.field",
		Tag:           "bytes,77702,opt,name=field",
		Filename:      "sf/substreams/sink/sql/schema/v1/schema.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional sf.substreams.sink.sql.schema.v1.Table table = 77701;
	E_Table = &file_sf_substreams_sink_sql_schema_v1_schema_proto_extTypes[0]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional sf.substreams.sink.sql.schema.v1.Column field = 77702;
	E_Field = &file_sf_substreams_sink_sql_schema_v1_schema_proto_extTypes[1]
)

var File_sf_substreams_sink_sql_schema_v1_schema_proto protoreflect.FileDescriptor

const file_sf_substreams_sink_sql_schema_v1_schema_proto_rawDesc = "" +
	"\n" +
	"-sf/substreams/sink/sql/schema/v1/schema.proto\x12 sf.substreams.sink.sql.schema.v1\x1a google/protobuf/descriptor.proto\"\xcf\x02\n" +
	"\x05Table\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1e\n" +
	"\bchild_of\x18\x02 \x01(\tH\x00R\achildOf\x88\x01\x01\x12[\n" +
	"\x0estorage_layout\x18\x04 \x01(\x0e2/.sf.substreams.sink.sql.schema.v1.StorageLayoutH\x01R\rstorageLayout\x88\x01\x01\x12x\n" +
	"\x18clickhouse_table_options\x18\xc8\x01 \x01(\v28.sf.substreams.sink.sql.schema.v1.ClickhouseTableOptionsH\x02R\x16clickhouseTableOptions\x88\x01\x01B\v\n" +
	"\t_child_ofB\x11\n" +
	"\x0f_storage_layoutB\x1b\n" +
	"\x19_clickhouse_table_options\"\x8b\x02\n" +
	"\x06Column\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tH\x00R\x04name\x88\x01\x01\x12$\n" +
	"\vforeign_key\x18\x02 \x01(\tH\x01R\n" +
	"foreignKey\x88\x01\x01\x12\x16\n" +
	"\x06unique\x18\x03 \x01(\bR\x06unique\x12\x1f\n" +
	"\vprimary_key\x18\x04 \x01(\bR\n" +
	"primaryKey\x12(\n" +
	"\rsemantic_type\x18\x05 \x01(\tH\x02R\fsemanticType\x88\x01\x01\x12$\n" +
	"\vformat_hint\x18\x06 \x01(\tH\x03R\n" +
	"formatHint\x88\x01\x01B\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_foreign_keyB\x10\n" +
	"\x0e_semantic_typeB\x0e\n" +
	"\f_format_hint\"\xa5\x03\n" +
	"\x16ClickhouseTableOptions\x12`\n" +
	"\x0forder_by_fields\x18\x01 \x03(\v28.sf.substreams.sink.sql.schema.v1.ClickhouseOrderByFieldR\rorderByFields\x12g\n" +
	"\x10partition_fields\x18\x02 \x03(\v2<.sf.substreams.sink.sql.schema.v1.ClickhousePartitionByFieldR\x0fpartitionFields\x12e\n" +
	"\x10replacing_fields\x18\x03 \x03(\v2:.sf.substreams.sink.sql.schema.v1.ClickhouseReplacingFieldR\x0freplacingFields\x12Y\n" +
	"\findex_fields\x18\x04 \x03(\v26.sf.substreams.sink.sql.schema.v1.ClickhouseIndexFieldR\vindexFields\"x\n" +
	"\x1aClickhousePartitionByField\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12F\n" +
	"\bfunction\x18\x02 \x01(\x0e2*.sf.substreams.sink.sql.schema.v1.FunctionR\bfunction\"\x94\x01\n" +
	"\x16ClickhouseOrderByField\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"descending\x18\x02 \x01(\bR\n" +
	"descending\x12F\n" +
	"\bfunction\x18\x03 \x01(\x0e2*.sf.substreams.sink.sql.schema.v1.FunctionR\bfunction\".\n" +
	"\x18ClickhouseReplacingField\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\xf4\x01\n" +
	"\x14ClickhouseIndexField\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"field_name\x18\x02 \x01(\tR\tfieldName\x12?\n" +
	"\x04type\x18\x03 \x01(\x0e2+.sf.substreams.sink.sql.schema.v1.IndexTypeR\x04type\x12 \n" +
	"\vgranularity\x18\x04 \x01(\rR\vgranularity\x12F\n" +
	"\bfunction\x18\x05 \x01(\x0e2*.sf.substreams.sink.sql.schema.v1.FunctionR\bfunction*R\n" +
	"\tIndexType\x12\n" +
	"\n" +
	"\x06minmax\x10\x00\x12\a\n" +
	"\x03set\x10\x01\x12\x0e\n" +
	"\n" +
	"ngrambf_v1\x10\x02\x12\x0e\n" +
	"\n" +
	"tokenbf_v1\x10\x03\x12\x10\n" +
	"\fbloom_filter\x10\x04*j\n" +
	"\bFunction\x12\t\n" +
	"\x05unset\x10\x00\x12\f\n" +
	"\btoYYYYMM\x10\x01\x12\f\n" +
	"\btoYYYYDD\x10\x02\x12\n" +
	"\n" +
	"\x06toYear\x10\x03\x12\v\n" +
	"\atoMonth\x10\x04\x12\n" +
	"\n" +
	"\x06toDate\x10\x05\x12\x12\n" +
	"\x0etoStartOfMonth\x10\x06*)\n" +
	"\rStorageLayout\x12\v\n" +
	"\aHUMMOCK\x10\x00\x12\v\n" +
	"\aICEBERG\x10\x01:`\n" +
	"\x05table\x12\x1f.google.protobuf.MessageOptions\x18\x85\xdf\x04 \x01(\v2'.sf.substreams.sink.sql.schema.v1.TableR\x05table:_\n" +
	"\x05field\x12\x1d.google.protobuf.FieldOptions\x18\x86\xdf\x04 \x01(\v2(.sf.substreams.sink.sql.schema.v1.ColumnR\x05fieldB\xac\x02\n" +
	"$com.sf.substreams.sink.sql.schema.v1B\vSchemaProtoP\x01ZPgithub.com/streamingfast/substreams-sink-sql/pb/sf/substreams/sink/sql/schema/v1\xa2\x02\x05SSSSS\xaa\x02 Sf.Substreams.Sink.Sql.Schema.V1\xca\x02 Sf\\Substreams\\Sink\\Sql\\Schema\\V1\xe2\x02,Sf\\Substreams\\Sink\\Sql\\Schema\\V1\\GPBMetadata\xea\x02%Sf::Substreams::Sink::Sql::Schema::V1b\x06proto3"

var (
	file_sf_substreams_sink_sql_schema_v1_schema_proto_rawDescOnce sync.Once
	file_sf_substreams_sink_sql_schema_v1_schema_proto_rawDescData []byte
)

func file_sf_substreams_sink_sql_schema_v1_schema_proto_rawDescGZIP() []byte {
	file_sf_substreams_sink_sql_schema_v1_schema_proto_rawDescOnce.Do(func() {
		file_sf_substreams_sink_sql_schema_v1_schema_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sf_substreams_sink_sql_schema_v1_schema_proto_rawDesc), len(file_sf_substreams_sink_sql_schema_v1_schema_proto_rawDesc)))
	})
	return file_sf_substreams_sink_sql_schema_v1_schema_proto_rawDescData
}

var file_sf_substreams_sink_sql_schema_v1_schema_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_sf_substreams_sink_sql_schema_v1_schema_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_sf_substreams_sink_sql_schema_v1_schema_proto_goTypes = []any{
	(IndexType)(0),                      // 0: sf.substreams.sink.sql.schema.v1.IndexType
	(Function)(0),                       // 1: sf.substreams.sink.sql.schema.v1.Function
	(StorageLayout)(0),                  // 2: sf.substreams.sink.sql.schema.v1.StorageLayout
	(*Table)(nil),                       // 3: sf.substreams.sink.sql.schema.v1.Table
	(*Column)(nil),                      // 4: sf.substreams.sink.sql.schema.v1.Column
	(*ClickhouseTableOptions)(nil),      // 5: sf.substreams.sink.sql.schema.v1.ClickhouseTableOptions
	(*ClickhousePartitionByField)(nil),  // 6: sf.substreams.sink.sql.schema.v1.ClickhousePartitionByField
	(*ClickhouseOrderByField)(nil),      // 7: sf.substreams.sink.sql.schema.v1.ClickhouseOrderByField
	(*ClickhouseReplacingField)(nil),    // 8: sf.substreams.sink.sql.schema.v1.ClickhouseReplacingField
	(*ClickhouseIndexField)(nil),        // 9: sf.substreams.sink.sql.schema.v1.ClickhouseIndexField
	(*descriptorpb.MessageOptions)(nil), // 10: google.protobuf.MessageOptions
	(*descriptorpb.FieldOptions)(nil),   // 11: google.protobuf.FieldOptions
}
var file_sf_substreams_sink_sql_schema_v1_schema_proto_depIdxs = []int32{
	2,  // 0: sf.substreams.sink.sql.schema.v1.Table.storage_layout:type_name -> sf.substreams.sink.sql.schema.v1.StorageLayout
	5,  // 1: sf.substreams.sink.sql.schema.v1.Table.clickhouse_table_options:type_name -> sf.substreams.sink.sql.schema.v1.ClickhouseTableOptions
	7,  // 2: sf.substreams.sink.sql.schema.v1.ClickhouseTableOptions.order_by_fields:type_name -> sf.substreams.sink.sql.schema.v1.ClickhouseOrderByField
	6,  // 3: sf.substreams.sink.sql.schema.v1.ClickhouseTableOptions.partition_fields:type_name -> sf.substreams.sink.sql.schema.v1.ClickhousePartitionByField
	8,  // 4: sf.substreams.sink.sql.schema.v1.ClickhouseTableOptions.replacing_fields:type_name -> sf.substreams.sink.sql.schema.v1.ClickhouseReplacingField
	9,  // 5: sf.substreams.sink.sql.schema.v1.ClickhouseTableOptions.index_fields:type_name -> sf.substreams.sink.sql.schema.v1.ClickhouseIndexField
	1,  // 6: sf.substreams.sink.sql.schema.v1.ClickhousePartitionByField.function:type_name -> sf.substreams.sink.sql.schema.v1.Function
	1,  // 7: sf.substreams.sink.sql.schema.v1.ClickhouseOrderByField.function:type_name -> sf.substreams.sink.sql.schema.v1.Function
	0,  // 8: sf.substreams.sink.sql.schema.v1.ClickhouseIndexField.type:type_name -> sf.substreams.sink.sql.schema.v1.IndexType
	1,  // 9: sf.substreams.sink.sql.schema.v1.ClickhouseIndexField.function:type_name -> sf.substreams.sink.sql.schema.v1.Function
	10, // 10: sf.substreams.sink.sql.schema.v1.table:extendee -> google.protobuf.MessageOptions
	11, // 11: sf.substreams.sink.sql.schema.v1.field:extendee -> google.protobuf.FieldOptions
	3,  // 12: sf.substreams.sink.sql.schema.v1.table:type_name -> sf.substreams.sink.sql.schema.v1.Table
	4,  // 13: sf.substreams.sink.sql.schema.v1.field:type_name -> sf.substreams.sink.sql.schema.v1.Column
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	12, // [12:14] is the sub-list for extension type_name
	10, // [10:12] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_sf_substreams_sink_sql_schema_v1_schema_proto_init() }
func file_sf_substreams_sink_sql_schema_v1_schema_proto_init() {
	if File_sf_substreams_sink_sql_schema_v1_schema_proto != nil {
		return
	}
	file_sf_substreams_sink_sql_schema_v1_schema_proto_msgTypes[0].OneofWrappers = []any{}
	file_sf_substreams_sink_sql_schema_v1_schema_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sf_substreams_sink_sql_schema_v1_schema_proto_rawDesc), len(file_sf_substreams_sink_sql_schema_v1_schema_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   7,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_sf_substreams_sink_sql_schema_v1_schema_proto_goTypes,
		DependencyIndexes: file_sf_substreams_sink_sql_schema_v1_schema_proto_depIdxs,
		EnumInfos:         file_sf_substreams_sink_sql_schema_v1_schema_proto_enumTypes,
		MessageInfos:      file_sf_substreams_sink_sql_schema_v1_schema_proto_msgTypes,
		ExtensionInfos:    file_sf_substreams_sink_sql_schema_v1_schema_proto_extTypes,
	}.Build()
	File_sf_substreams_sink_sql_schema_v1_schema_proto = out.File
	file_sf_substreams_sink_sql_schema_v1_schema_proto_goTypes = nil
	file_sf_substreams_sink_sql_schema_v1_schema_proto_depIdxs = nil
}
