// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: sf/substreams/sink/sql/schema/v1/schema.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Table struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Name    string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ChildOf *string                `protobuf:"bytes,2,opt,name=child_of,json=childOf,proto3,oneof" json:"child_of,omitempty"`
	// should be remove
	ManyToOneRelationFieldName string `protobuf:"bytes,81,opt,name=many_to_one_relation_field_name,json=manyToOneRelationFieldName,proto3" json:"many_to_one_relation_field_name,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *Table) Reset() {
	*x = Table{}
	mi := &file_sf_substreams_sink_sql_schema_v1_schema_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Table) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Table) ProtoMessage() {}

func (x *Table) ProtoReflect() protoreflect.Message {
	mi := &file_sf_substreams_sink_sql_schema_v1_schema_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Table.ProtoReflect.Descriptor instead.
func (*Table) Descriptor() ([]byte, []int) {
	return file_sf_substreams_sink_sql_schema_v1_schema_proto_rawDescGZIP(), []int{0}
}

func (x *Table) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Table) GetChildOf() string {
	if x != nil && x.ChildOf != nil {
		return *x.ChildOf
	}
	return ""
}

func (x *Table) GetManyToOneRelationFieldName() string {
	if x != nil {
		return x.ManyToOneRelationFieldName
	}
	return ""
}

type Column struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Name       *string                `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	ForeignKey *string                `protobuf:"bytes,2,opt,name=foreign_key,json=foreignKey,proto3,oneof" json:"foreign_key,omitempty"`
	Unique     bool                   `protobuf:"varint,3,opt,name=unique,proto3" json:"unique,omitempty"`
	PrimaryKey bool                   `protobuf:"varint,4,opt,name=primary_key,json=primaryKey,proto3" json:"primary_key,omitempty"`
	// Semantic type annotation for custom SQL type mapping
	SemanticType  *string `protobuf:"bytes,5,opt,name=semantic_type,json=semanticType,proto3,oneof" json:"semantic_type,omitempty"` // Semantic type hint (e.g., "uint256", "address")
	FormatHint    *string `protobuf:"bytes,6,opt,name=format_hint,json=formatHint,proto3,oneof" json:"format_hint,omitempty"`       // Format hint for conversion (e.g., "hex", "decimal")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Column) Reset() {
	*x = Column{}
	mi := &file_sf_substreams_sink_sql_schema_v1_schema_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Column) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Column) ProtoMessage() {}

func (x *Column) ProtoReflect() protoreflect.Message {
	mi := &file_sf_substreams_sink_sql_schema_v1_schema_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Column.ProtoReflect.Descriptor instead.
func (*Column) Descriptor() ([]byte, []int) {
	return file_sf_substreams_sink_sql_schema_v1_schema_proto_rawDescGZIP(), []int{1}
}

func (x *Column) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *Column) GetForeignKey() string {
	if x != nil && x.ForeignKey != nil {
		return *x.ForeignKey
	}
	return ""
}

func (x *Column) GetUnique() bool {
	if x != nil {
		return x.Unique
	}
	return false
}

func (x *Column) GetPrimaryKey() bool {
	if x != nil {
		return x.PrimaryKey
	}
	return false
}

func (x *Column) GetSemanticType() string {
	if x != nil && x.SemanticType != nil {
		return *x.SemanticType
	}
	return ""
}

func (x *Column) GetFormatHint() string {
	if x != nil && x.FormatHint != nil {
		return *x.FormatHint
	}
	return ""
}

var file_sf_substreams_sink_sql_schema_v1_schema_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*Table)(nil),
		Field:         77701,
		Name:          "sf.substreams.sink.sql.schema.v1.table",
		Tag:           "bytes,77701,opt,name=table",
		Filename:      "sf/substreams/sink/sql/schema/v1/schema.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*Column)(nil),
		Field:         77702,
		Name:          "sf.substreams.sink.sql.schema.v1.field",
		Tag:           "bytes,77702,opt,name=field",
		Filename:      "sf/substreams/sink/sql/schema/v1/schema.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional sf.substreams.sink.sql.schema.v1.Table table = 77701;
	E_Table = &file_sf_substreams_sink_sql_schema_v1_schema_proto_extTypes[0]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional sf.substreams.sink.sql.schema.v1.Column field = 77702;
	E_Field = &file_sf_substreams_sink_sql_schema_v1_schema_proto_extTypes[1] //todo: ignore
)

var File_sf_substreams_sink_sql_schema_v1_schema_proto protoreflect.FileDescriptor

const file_sf_substreams_sink_sql_schema_v1_schema_proto_rawDesc = "" +
	"\n" +
	"-sf/substreams/sink/sql/schema/v1/schema.proto\x12 sf.substreams.sink.sql.schema.v1\x1a google/protobuf/descriptor.proto\"\x8d\x01\n" +
	"\x05Table\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1e\n" +
	"\bchild_of\x18\x02 \x01(\tH\x00R\achildOf\x88\x01\x01\x12C\n" +
	"\x1fmany_to_one_relation_field_name\x18Q \x01(\tR\x1amanyToOneRelationFieldNameB\v\n" +
	"\t_child_of\"\x8b\x02\n" +
	"\x06Column\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tH\x00R\x04name\x88\x01\x01\x12$\n" +
	"\vforeign_key\x18\x02 \x01(\tH\x01R\n" +
	"foreignKey\x88\x01\x01\x12\x16\n" +
	"\x06unique\x18\x03 \x01(\bR\x06unique\x12\x1f\n" +
	"\vprimary_key\x18\x04 \x01(\bR\n" +
	"primaryKey\x12(\n" +
	"\rsemantic_type\x18\x05 \x01(\tH\x02R\fsemanticType\x88\x01\x01\x12$\n" +
	"\vformat_hint\x18\x06 \x01(\tH\x03R\n" +
	"formatHint\x88\x01\x01B\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_foreign_keyB\x10\n" +
	"\x0e_semantic_typeB\x0e\n" +
	"\f_format_hint:`\n" +
	"\x05table\x12\x1f.google.protobuf.MessageOptions\x18\x85\xdf\x04 \x01(\v2'.sf.substreams.sink.sql.schema.v1.TableR\x05table:_\n" +
	"\x05field\x12\x1d.google.protobuf.FieldOptions\x18\x86\xdf\x04 \x01(\v2(.sf.substreams.sink.sql.schema.v1.ColumnR\x05fieldB\xac\x02\n" +
	"$com.sf.substreams.sink.sql.schema.v1B\vSchemaProtoP\x01ZPgithub.com/streamingfast/substreams-sink-sql/pb/sf/substreams/sink/sql/schema/v1\xa2\x02\x05SSSSS\xaa\x02 Sf.Substreams.Sink.Sql.Schema.V1\xca\x02 Sf\\Substreams\\Sink\\Sql\\Schema\\V1\xe2\x02,Sf\\Substreams\\Sink\\Sql\\Schema\\V1\\GPBMetadata\xea\x02%Sf::Substreams::Sink::Sql::Schema::V1b\x06proto3"

var (
	file_sf_substreams_sink_sql_schema_v1_schema_proto_rawDescOnce sync.Once
	file_sf_substreams_sink_sql_schema_v1_schema_proto_rawDescData []byte
)

func file_sf_substreams_sink_sql_schema_v1_schema_proto_rawDescGZIP() []byte {
	file_sf_substreams_sink_sql_schema_v1_schema_proto_rawDescOnce.Do(func() {
		file_sf_substreams_sink_sql_schema_v1_schema_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sf_substreams_sink_sql_schema_v1_schema_proto_rawDesc), len(file_sf_substreams_sink_sql_schema_v1_schema_proto_rawDesc)))
	})
	return file_sf_substreams_sink_sql_schema_v1_schema_proto_rawDescData
}

var file_sf_substreams_sink_sql_schema_v1_schema_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sf_substreams_sink_sql_schema_v1_schema_proto_goTypes = []any{
	(*Table)(nil),                       // 0: sf.substreams.sink.sql.schema.v1.Table
	(*Column)(nil),                      // 1: sf.substreams.sink.sql.schema.v1.Column
	(*descriptorpb.MessageOptions)(nil), // 2: google.protobuf.MessageOptions
	(*descriptorpb.FieldOptions)(nil),   // 3: google.protobuf.FieldOptions
}
var file_sf_substreams_sink_sql_schema_v1_schema_proto_depIdxs = []int32{
	2, // 0: sf.substreams.sink.sql.schema.v1.table:extendee -> google.protobuf.MessageOptions
	3, // 1: sf.substreams.sink.sql.schema.v1.field:extendee -> google.protobuf.FieldOptions
	0, // 2: sf.substreams.sink.sql.schema.v1.table:type_name -> sf.substreams.sink.sql.schema.v1.Table
	1, // 3: sf.substreams.sink.sql.schema.v1.field:type_name -> sf.substreams.sink.sql.schema.v1.Column
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	2, // [2:4] is the sub-list for extension type_name
	0, // [0:2] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sf_substreams_sink_sql_schema_v1_schema_proto_init() }
func file_sf_substreams_sink_sql_schema_v1_schema_proto_init() {
	if File_sf_substreams_sink_sql_schema_v1_schema_proto != nil {
		return
	}
	file_sf_substreams_sink_sql_schema_v1_schema_proto_msgTypes[0].OneofWrappers = []any{}
	file_sf_substreams_sink_sql_schema_v1_schema_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sf_substreams_sink_sql_schema_v1_schema_proto_rawDesc), len(file_sf_substreams_sink_sql_schema_v1_schema_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_sf_substreams_sink_sql_schema_v1_schema_proto_goTypes,
		DependencyIndexes: file_sf_substreams_sink_sql_schema_v1_schema_proto_depIdxs,
		MessageInfos:      file_sf_substreams_sink_sql_schema_v1_schema_proto_msgTypes,
		ExtensionInfos:    file_sf_substreams_sink_sql_schema_v1_schema_proto_extTypes,
	}.Build()
	File_sf_substreams_sink_sql_schema_v1_schema_proto = out.File
	file_sf_substreams_sink_sql_schema_v1_schema_proto_goTypes = nil
	file_sf_substreams_sink_sql_schema_v1_schema_proto_depIdxs = nil
}
