// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: test/relations/relations.proto

package relations

import (
	_ "github.com/streamingfast/substreams-sink-sql/pb/sf/substreams/sink/sql/schema/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/descriptorpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Output struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entities      []*Entity              `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Output) Reset() {
	*x = Output{}
	mi := &file_test_relations_relations_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Output) ProtoMessage() {}

func (x *Output) ProtoReflect() protoreflect.Message {
	mi := &file_test_relations_relations_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Output.ProtoReflect.Descriptor instead.
func (*Output) Descriptor() ([]byte, []int) {
	return file_test_relations_relations_proto_rawDescGZIP(), []int{0}
}

func (x *Output) GetEntities() []*Entity {
	if x != nil {
		return x.Entities
	}
	return nil
}

type Entity struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Entity:
	//
	//	*Entity_TypesTest
	//	*Entity_Customer
	//	*Entity_Order
	//	*Entity_Item
	Entity        isEntity_Entity `protobuf_oneof:"entity"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entity) Reset() {
	*x = Entity{}
	mi := &file_test_relations_relations_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entity) ProtoMessage() {}

func (x *Entity) ProtoReflect() protoreflect.Message {
	mi := &file_test_relations_relations_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entity.ProtoReflect.Descriptor instead.
func (*Entity) Descriptor() ([]byte, []int) {
	return file_test_relations_relations_proto_rawDescGZIP(), []int{1}
}

func (x *Entity) GetEntity() isEntity_Entity {
	if x != nil {
		return x.Entity
	}
	return nil
}

func (x *Entity) GetTypesTest() *TypesTest {
	if x != nil {
		if x, ok := x.Entity.(*Entity_TypesTest); ok {
			return x.TypesTest
		}
	}
	return nil
}

func (x *Entity) GetCustomer() *Customer {
	if x != nil {
		if x, ok := x.Entity.(*Entity_Customer); ok {
			return x.Customer
		}
	}
	return nil
}

func (x *Entity) GetOrder() *Order {
	if x != nil {
		if x, ok := x.Entity.(*Entity_Order); ok {
			return x.Order
		}
	}
	return nil
}

func (x *Entity) GetItem() *Item {
	if x != nil {
		if x, ok := x.Entity.(*Entity_Item); ok {
			return x.Item
		}
	}
	return nil
}

type isEntity_Entity interface {
	isEntity_Entity()
}

type Entity_TypesTest struct {
	TypesTest *TypesTest `protobuf:"bytes,1,opt,name=types_test,json=typesTest,proto3,oneof"`
}

type Entity_Customer struct {
	Customer *Customer `protobuf:"bytes,10,opt,name=customer,proto3,oneof"`
}

type Entity_Order struct {
	Order *Order `protobuf:"bytes,11,opt,name=order,proto3,oneof"`
}

type Entity_Item struct {
	Item *Item `protobuf:"bytes,12,opt,name=item,proto3,oneof"`
}

func (*Entity_TypesTest) isEntity_Entity() {}

func (*Entity_Customer) isEntity_Entity() {}

func (*Entity_Order) isEntity_Entity() {}

func (*Entity_Item) isEntity_Entity() {}

type TypesTest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Field for each protobuf native type
	DoubleField    float64                `protobuf:"fixed64,2,opt,name=double_field,json=doubleField,proto3" json:"double_field,omitempty"`
	FloatField     float32                `protobuf:"fixed32,3,opt,name=float_field,json=floatField,proto3" json:"float_field,omitempty"`
	Int32Field     int32                  `protobuf:"varint,4,opt,name=int32_field,json=int32Field,proto3" json:"int32_field,omitempty"`
	Int64Field     int64                  `protobuf:"varint,5,opt,name=int64_field,json=int64Field,proto3" json:"int64_field,omitempty"`
	Uint32Field    uint32                 `protobuf:"varint,6,opt,name=uint32_field,json=uint32Field,proto3" json:"uint32_field,omitempty"`
	Uint64Field    uint64                 `protobuf:"varint,7,opt,name=uint64_field,json=uint64Field,proto3" json:"uint64_field,omitempty"`
	Sint32Field    int32                  `protobuf:"zigzag32,8,opt,name=sint32_field,json=sint32Field,proto3" json:"sint32_field,omitempty"`
	Sint64Field    int64                  `protobuf:"zigzag64,9,opt,name=sint64_field,json=sint64Field,proto3" json:"sint64_field,omitempty"`
	Fixed32Field   uint32                 `protobuf:"fixed32,10,opt,name=fixed32_field,json=fixed32Field,proto3" json:"fixed32_field,omitempty"`
	Fixed64Field   uint64                 `protobuf:"fixed64,11,opt,name=fixed64_field,json=fixed64Field,proto3" json:"fixed64_field,omitempty"`
	Sfixed32Field  int32                  `protobuf:"fixed32,12,opt,name=sfixed32_field,json=sfixed32Field,proto3" json:"sfixed32_field,omitempty"`
	Sfixed64Field  int64                  `protobuf:"fixed64,13,opt,name=sfixed64_field,json=sfixed64Field,proto3" json:"sfixed64_field,omitempty"`
	BoolField      bool                   `protobuf:"varint,14,opt,name=bool_field,json=boolField,proto3" json:"bool_field,omitempty"`
	StringField    string                 `protobuf:"bytes,15,opt,name=string_field,json=stringField,proto3" json:"string_field,omitempty"`
	BytesField     []byte                 `protobuf:"bytes,16,opt,name=bytes_field,json=bytesField,proto3" json:"bytes_field,omitempty"`
	TimestampField *timestamppb.Timestamp `protobuf:"bytes,30,opt,name=timestamp_field,json=timestampField,proto3" json:"timestamp_field,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TypesTest) Reset() {
	*x = TypesTest{}
	mi := &file_test_relations_relations_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypesTest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypesTest) ProtoMessage() {}

func (x *TypesTest) ProtoReflect() protoreflect.Message {
	mi := &file_test_relations_relations_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypesTest.ProtoReflect.Descriptor instead.
func (*TypesTest) Descriptor() ([]byte, []int) {
	return file_test_relations_relations_proto_rawDescGZIP(), []int{2}
}

func (x *TypesTest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TypesTest) GetDoubleField() float64 {
	if x != nil {
		return x.DoubleField
	}
	return 0
}

func (x *TypesTest) GetFloatField() float32 {
	if x != nil {
		return x.FloatField
	}
	return 0
}

func (x *TypesTest) GetInt32Field() int32 {
	if x != nil {
		return x.Int32Field
	}
	return 0
}

func (x *TypesTest) GetInt64Field() int64 {
	if x != nil {
		return x.Int64Field
	}
	return 0
}

func (x *TypesTest) GetUint32Field() uint32 {
	if x != nil {
		return x.Uint32Field
	}
	return 0
}

func (x *TypesTest) GetUint64Field() uint64 {
	if x != nil {
		return x.Uint64Field
	}
	return 0
}

func (x *TypesTest) GetSint32Field() int32 {
	if x != nil {
		return x.Sint32Field
	}
	return 0
}

func (x *TypesTest) GetSint64Field() int64 {
	if x != nil {
		return x.Sint64Field
	}
	return 0
}

func (x *TypesTest) GetFixed32Field() uint32 {
	if x != nil {
		return x.Fixed32Field
	}
	return 0
}

func (x *TypesTest) GetFixed64Field() uint64 {
	if x != nil {
		return x.Fixed64Field
	}
	return 0
}

func (x *TypesTest) GetSfixed32Field() int32 {
	if x != nil {
		return x.Sfixed32Field
	}
	return 0
}

func (x *TypesTest) GetSfixed64Field() int64 {
	if x != nil {
		return x.Sfixed64Field
	}
	return 0
}

func (x *TypesTest) GetBoolField() bool {
	if x != nil {
		return x.BoolField
	}
	return false
}

func (x *TypesTest) GetStringField() string {
	if x != nil {
		return x.StringField
	}
	return ""
}

func (x *TypesTest) GetBytesField() []byte {
	if x != nil {
		return x.BytesField
	}
	return nil
}

func (x *TypesTest) GetTimestampField() *timestamppb.Timestamp {
	if x != nil {
		return x.TimestampField
	}
	return nil
}

type Customer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    string                 `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Customer) Reset() {
	*x = Customer{}
	mi := &file_test_relations_relations_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Customer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Customer) ProtoMessage() {}

func (x *Customer) ProtoReflect() protoreflect.Message {
	mi := &file_test_relations_relations_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Customer.ProtoReflect.Descriptor instead.
func (*Customer) Descriptor() ([]byte, []int) {
	return file_test_relations_relations_proto_rawDescGZIP(), []int{3}
}

func (x *Customer) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *Customer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	CustomerRefId string                 `protobuf:"bytes,2,opt,name=customer_ref_id,json=customerRefId,proto3" json:"customer_ref_id,omitempty"`
	Items         []*OrderItem           `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_test_relations_relations_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_test_relations_relations_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_test_relations_relations_proto_rawDescGZIP(), []int{4}
}

func (x *Order) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *Order) GetCustomerRefId() string {
	if x != nil {
		return x.CustomerRefId
	}
	return ""
}

func (x *Order) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type OrderItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// can also leverage orders._id using "order on order_id" if order do not have a external unique identifier
	ItemId        string `protobuf:"bytes,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Quantity      int64  `protobuf:"varint,11,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_test_relations_relations_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_test_relations_relations_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_test_relations_relations_proto_rawDescGZIP(), []int{5}
}

func (x *OrderItem) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *OrderItem) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Name          string                 `protobuf:"bytes,10,opt,name=name,proto3" json:"name,omitempty"`
	Price         float64                `protobuf:"fixed64,11,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_test_relations_relations_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_test_relations_relations_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_test_relations_relations_proto_rawDescGZIP(), []int{6}
}

func (x *Item) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Item) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

var File_test_relations_relations_proto protoreflect.FileDescriptor

const file_test_relations_relations_proto_rawDesc = "" +
	"\n" +
	"\x1etest/relations/relations.proto\x12\x0etest.relations\x1a google/protobuf/descriptor.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a-sf/substreams/sink/sql/schema/v1/schema.proto\"<\n" +
	"\x06Output\x122\n" +
	"\bentities\x18\x01 \x03(\v2\x16.test.relations.EntityR\bentities\"\xe1\x01\n" +
	"\x06Entity\x12:\n" +
	"\n" +
	"types_test\x18\x01 \x01(\v2\x19.test.relations.TypesTestH\x00R\ttypesTest\x126\n" +
	"\bcustomer\x18\n" +
	" \x01(\v2\x18.test.relations.CustomerH\x00R\bcustomer\x12-\n" +
	"\x05order\x18\v \x01(\v2\x15.test.relations.OrderH\x00R\x05order\x12*\n" +
	"\x04item\x18\f \x01(\v2\x14.test.relations.ItemH\x00R\x04itemB\b\n" +
	"\x06entity\"\x88\x05\n" +
	"\tTypesTest\x12\x16\n" +
	"\x02id\x18\x01 \x01(\x04B\x06\xb2\xf8%\x02 \x01R\x02id\x12!\n" +
	"\fdouble_field\x18\x02 \x01(\x01R\vdoubleField\x12\x1f\n" +
	"\vfloat_field\x18\x03 \x01(\x02R\n" +
	"floatField\x12\x1f\n" +
	"\vint32_field\x18\x04 \x01(\x05R\n" +
	"int32Field\x12\x1f\n" +
	"\vint64_field\x18\x05 \x01(\x03R\n" +
	"int64Field\x12!\n" +
	"\fuint32_field\x18\x06 \x01(\rR\vuint32Field\x12!\n" +
	"\fuint64_field\x18\a \x01(\x04R\vuint64Field\x12!\n" +
	"\fsint32_field\x18\b \x01(\x11R\vsint32Field\x12!\n" +
	"\fsint64_field\x18\t \x01(\x12R\vsint64Field\x12#\n" +
	"\rfixed32_field\x18\n" +
	" \x01(\aR\ffixed32Field\x12#\n" +
	"\rfixed64_field\x18\v \x01(\x06R\ffixed64Field\x12%\n" +
	"\x0esfixed32_field\x18\f \x01(\x0fR\rsfixed32Field\x12%\n" +
	"\x0esfixed64_field\x18\r \x01(\x10R\rsfixed64Field\x12\x1d\n" +
	"\n" +
	"bool_field\x18\x0e \x01(\bR\tboolField\x12!\n" +
	"\fstring_field\x18\x0f \x01(\tR\vstringField\x12\x1f\n" +
	"\vbytes_field\x18\x10 \x01(\fR\n" +
	"bytesField\x12C\n" +
	"\x0ftimestamp_field\x18\x1e \x01(\v2\x1a.google.protobuf.TimestampR\x0etimestampField:\x11\xaa\xf8%\r\n" +
	"\vtypes_tests\"X\n" +
	"\bCustomer\x12'\n" +
	"\vcustomer_id\x18\x01 \x01(\tB\x06\xb2\xf8%\x02 \x01R\n" +
	"customerId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name:\x0f\xaa\xf8%\v\n" +
	"\tcustomers\"\xb1\x01\n" +
	"\x05Order\x12!\n" +
	"\border_id\x18\x01 \x01(\tB\x06\xb2\xf8%\x02 \x01R\aorderId\x12F\n" +
	"\x0fcustomer_ref_id\x18\x02 \x01(\tB\x1e\xb2\xf8%\x1a\x12\x18customers on customer_idR\rcustomerRefId\x12/\n" +
	"\x05items\x18\x03 \x03(\v2\x19.test.relations.OrderItemR\x05items:\f\xaa\xf8%\b\n" +
	"\x06orders\"\x7f\n" +
	"\tOrderItem\x12/\n" +
	"\aitem_id\x18\x02 \x01(\tB\x16\xb2\xf8%\x12\x12\x10items on item_idR\x06itemId\x12\x1a\n" +
	"\bquantity\x18\v \x01(\x03R\bquantity:%\xaa\xf8%!\n" +
	"\vorder_items\x12\x12orders on order_id\"^\n" +
	"\x04Item\x12\x1f\n" +
	"\aitem_id\x18\x01 \x01(\tB\x06\xb2\xf8%\x02\x18\x01R\x06itemId\x12\x12\n" +
	"\x04name\x18\n" +
	" \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\v \x01(\x01R\x05price:\v\xaa\xf8%\a\n" +
	"\x05itemsB\x8d\x01\n" +
	"\x12com.test.relationsB\x0eRelationsProtoP\x01Z\x0etest/relations\xa2\x02\x03TRX\xaa\x02\x0eTest.Relations\xca\x02\x0eTest\\Relations\xe2\x02\x1aTest\\Relations\\GPBMetadata\xea\x02\x0fTest::Relationsb\x06proto3"

var (
	file_test_relations_relations_proto_rawDescOnce sync.Once
	file_test_relations_relations_proto_rawDescData []byte
)

func file_test_relations_relations_proto_rawDescGZIP() []byte {
	file_test_relations_relations_proto_rawDescOnce.Do(func() {
		file_test_relations_relations_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_test_relations_relations_proto_rawDesc), len(file_test_relations_relations_proto_rawDesc)))
	})
	return file_test_relations_relations_proto_rawDescData
}

var file_test_relations_relations_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_test_relations_relations_proto_goTypes = []any{
	(*Output)(nil),                // 0: test.relations.Output
	(*Entity)(nil),                // 1: test.relations.Entity
	(*TypesTest)(nil),             // 2: test.relations.TypesTest
	(*Customer)(nil),              // 3: test.relations.Customer
	(*Order)(nil),                 // 4: test.relations.Order
	(*OrderItem)(nil),             // 5: test.relations.OrderItem
	(*Item)(nil),                  // 6: test.relations.Item
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_test_relations_relations_proto_depIdxs = []int32{
	1, // 0: test.relations.Output.entities:type_name -> test.relations.Entity
	2, // 1: test.relations.Entity.types_test:type_name -> test.relations.TypesTest
	3, // 2: test.relations.Entity.customer:type_name -> test.relations.Customer
	4, // 3: test.relations.Entity.order:type_name -> test.relations.Order
	6, // 4: test.relations.Entity.item:type_name -> test.relations.Item
	7, // 5: test.relations.TypesTest.timestamp_field:type_name -> google.protobuf.Timestamp
	5, // 6: test.relations.Order.items:type_name -> test.relations.OrderItem
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_test_relations_relations_proto_init() }
func file_test_relations_relations_proto_init() {
	if File_test_relations_relations_proto != nil {
		return
	}
	file_test_relations_relations_proto_msgTypes[1].OneofWrappers = []any{
		(*Entity_TypesTest)(nil),
		(*Entity_Customer)(nil),
		(*Entity_Order)(nil),
		(*Entity_Item)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_test_relations_relations_proto_rawDesc), len(file_test_relations_relations_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_test_relations_relations_proto_goTypes,
		DependencyIndexes: file_test_relations_relations_proto_depIdxs,
		MessageInfos:      file_test_relations_relations_proto_msgTypes,
	}.Build()
	File_test_relations_relations_proto = out.File
	file_test_relations_relations_proto_goTypes = nil
	file_test_relations_relations_proto_depIdxs = nil
}
